### ISSUE TITLE
Maintaining this package?

### ISSUE THREAD

**Issue by epatters** [phil-mansfield/UnionFind.jl#1]
Hi @phil-mansfield, thanks for writing this package. I've updated [my fork](https://github.com/epatters/UnionFind.jl) for Julia v1.0 and am using it in one of my packages.

I'd like to see this package added to the [official registry](https://github.com/JuliaLang/METADATA.jl). Are you interested in maintaining this package? If so, I can make a PR to update it and you could register it. If not, I could add my fork to the registry. Please let me know if you have a preference.

**Comment by phil-mansfield** [comment]
Thanks for checking in. I'm glad to hear you found it useful.

I don't think I'd have time to maintain this (or to relearn Julia, really), so feel free to add your fork to the registry.

**Comment by epatters** [comment]
Thanks @phil-mansfield, I'll do that.
